# Generated by Django 6.0.4 on 2026-04-23 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oggie', '0002_cat_found_address_cat_found_lat_cat_found_lng_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one active announcement per foundation is allowed. Activating this will deactivate any other active announcement from your foundation.'),
        ),
        migrations.AlterField(
            model_name='feedingsite',
            name='point_person',
            field=models.ForeignKey(blank=True, help_text='Volunteer/coordinator responsible for this site. Choose from your foundation members.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_sites_managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
