# Generated by Django 6.0.4 on 2026-04-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oggie', '0003_alter_announcement_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='birthday',
            field=models.DateField(blank=True, help_text='Exact birthday if known. If left blank, use "estimated age" below.', null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='is_neutered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cat',
            name='is_vaccinated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cat',
            name='parents',
            field=models.ManyToManyField(blank=True, help_text='Known parents of this cat (adds this cat as their child automatically).', related_name='children', to='Oggie.cat'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='age_years',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Estimated age in years — used only if birthday is unknown.', null=True),
        ),
    ]
