# Generated by Django 6.0.4 on 2026-04-23 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oggie', '0004_cat_birthday_cat_is_neutered_cat_is_vaccinated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingsite',
            name='point_person',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='foundation',
        ),
        migrations.AddField(
            model_name='feedingsite',
            name='contact_details',
            field=models.CharField(blank=True, help_text='Phone, email, or anything else volunteers should use to reach the point person(s).', max_length=200),
        ),
        migrations.AddField(
            model_name='feedingsite',
            name='point_persons',
            field=models.ManyToManyField(blank=True, help_text='Staff members coordinating this site. Pick one or more.', related_name='feeding_sites_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='foundations',
            field=models.ManyToManyField(blank=True, help_text='Foundations this user belongs to. A user can belong to multiple foundations.', related_name='members', to='Oggie.foundation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('adopter', 'Adopter/Donor'), ('foundation', 'Foundation Partner'), ('staff', 'Oggie Staff')], default='adopter', max_length=20),
        ),
    ]
