# Generated by Django 6.0.4 on 2026-04-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oggie', '0005_remove_feedingsite_point_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='description',
            field=models.TextField(blank=True, help_text='Highly encouraged — color, markings, temperament, medical notes, etc.'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cats/'),
        ),
    ]
