# Generated by Django 6.0.4 on 2026-04-23 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oggie', '0006_alter_cat_description_alter_cat_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foundation',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='Admins can add/remove members and promote other members to admin. All admins must also be members of this foundation.', related_name='foundations_as_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
