# Generated by Django 6.0.4 on 2026-04-24 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oggie', '0007_foundation_admins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(blank=True, help_text='For anonymous reporters', max_length=100)),
                ('reporter_email', models.EmailField(blank=True, help_text='For follow-up (optional)', max_length=254)),
                ('incident_type', models.CharField(choices=[('injured', 'Injured'), ('sick', 'Sick / needs medical help'), ('abandoned', 'Abandoned / left behind'), ('missing', 'Missing / not at usual spot'), ('other', 'Other concern')], max_length=20)),
                ('description', models.TextField(help_text='Describe what you observed — be as specific as possible.')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='incidents/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('foundation_notes', models.TextField(blank=True, help_text='Notes added by the foundation when acknowledging or resolving.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='Oggie.cat')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
