# Generated by Django 6.0.4 on 2026-04-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oggie', '0009_alter_donation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catincident',
            name='incident_type',
            field=models.CharField(choices=[('injured', 'Injured'), ('sick', 'Sick / needs medical help'), ('abandoned', 'Abandoned / left behind'), ('missing', 'Missing / not at usual spot'), ('update_info', 'Update cat info'), ('other', 'Other concern')], max_length=20),
        ),
    ]
